// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Discord.OpenApiClient.Channels.Item.Polls.Item.Answers.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Discord.OpenApiClient.Channels.Item.Polls.Item.Answers
{
    /// <summary>
    /// Builds and executes requests for operations under \channels\{channel_id}\polls\{message_id}\answers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnswersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Discord.OpenApiClient.channels.item.polls.item.answers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.Polls.Item.Answers.Item.WithAnswer_ItemRequestBuilder"/></returns>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Polls.Item.Answers.Item.WithAnswer_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("answer_id", position);
                return new global::Soenneker.Discord.OpenApiClient.Channels.Item.Polls.Item.Answers.Item.WithAnswer_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.Polls.Item.Answers.AnswersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnswersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/channels/{channel_id}/polls/{message_id}/answers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.Polls.Item.Answers.AnswersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnswersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/channels/{channel_id}/polls/{message_id}/answers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
