// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Discord.OpenApiClient.Oauth2.Applications;
using Soenneker.Discord.OpenApiClient.Oauth2.Keys;
using Soenneker.Discord.OpenApiClient.Oauth2.Me;
using Soenneker.Discord.OpenApiClient.Oauth2.Userinfo;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Discord.OpenApiClient.Oauth2
{
    /// <summary>
    /// Builds and executes requests for operations under \oauth2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Oauth2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The applications property</summary>
        public global::Soenneker.Discord.OpenApiClient.Oauth2.Applications.ApplicationsRequestBuilder Applications
        {
            get => new global::Soenneker.Discord.OpenApiClient.Oauth2.Applications.ApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.Discord.OpenApiClient.Oauth2.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.Discord.OpenApiClient.Oauth2.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Me property</summary>
        public global::Soenneker.Discord.OpenApiClient.Oauth2.Me.MeRequestBuilder Me
        {
            get => new global::Soenneker.Discord.OpenApiClient.Oauth2.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userinfo property</summary>
        public global::Soenneker.Discord.OpenApiClient.Oauth2.Userinfo.UserinfoRequestBuilder Userinfo
        {
            get => new global::Soenneker.Discord.OpenApiClient.Oauth2.Userinfo.UserinfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Oauth2.Oauth2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Oauth2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Oauth2.Oauth2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Oauth2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/oauth2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
