// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Discord.OpenApiClient.Interactions.Item.Item.Callback;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Discord.OpenApiClient.Interactions.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \interactions\{interaction_id}\{interaction_token}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithInteraction_tokenItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The callback property</summary>
        public global::Soenneker.Discord.OpenApiClient.Interactions.Item.Item.Callback.CallbackRequestBuilder Callback
        {
            get => new global::Soenneker.Discord.OpenApiClient.Interactions.Item.Item.Callback.CallbackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Interactions.Item.Item.WithInteraction_tokenItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInteraction_tokenItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interactions/{interaction_id}/{interaction_token}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Interactions.Item.Item.WithInteraction_tokenItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInteraction_tokenItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/interactions/{interaction_id}/{interaction_token}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
