// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ActionRowComponentForMessageRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The components property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components>? Components { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components> Components { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest"/> and sets the default values.
        /// </summary>
        public ActionRowComponentForMessageRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "components", n => { Components = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components>(global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components>("components", Components);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.ButtonComponentForMessageRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ChannelSelectComponentForMessageRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.MentionableSelectComponentForMessageRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentForMessageRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.StringSelectComponentForMessageRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserSelectComponentForMessageRequest"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActionRowComponentForMessageRequest_components : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ButtonComponentForMessageRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ButtonComponentForMessageRequest? ButtonComponentForMessageRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ButtonComponentForMessageRequest ButtonComponentForMessageRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ChannelSelectComponentForMessageRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ChannelSelectComponentForMessageRequest? ChannelSelectComponentForMessageRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ChannelSelectComponentForMessageRequest ChannelSelectComponentForMessageRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.MentionableSelectComponentForMessageRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.MentionableSelectComponentForMessageRequest? MentionableSelectComponentForMessageRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.MentionableSelectComponentForMessageRequest MentionableSelectComponentForMessageRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentForMessageRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentForMessageRequest? RoleSelectComponentForMessageRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentForMessageRequest RoleSelectComponentForMessageRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.StringSelectComponentForMessageRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.StringSelectComponentForMessageRequest? StringSelectComponentForMessageRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.StringSelectComponentForMessageRequest StringSelectComponentForMessageRequest { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserSelectComponentForMessageRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserSelectComponentForMessageRequest? UserSelectComponentForMessageRequest { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserSelectComponentForMessageRequest UserSelectComponentForMessageRequest { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.ActionRowComponentForMessageRequest.ActionRowComponentForMessageRequest_components();
                if("ButtonComponentForMessageRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ButtonComponentForMessageRequest = new global::Soenneker.Discord.OpenApiClient.Models.ButtonComponentForMessageRequest();
                }
                else if("ChannelSelectComponentForMessageRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ChannelSelectComponentForMessageRequest = new global::Soenneker.Discord.OpenApiClient.Models.ChannelSelectComponentForMessageRequest();
                }
                else if("MentionableSelectComponentForMessageRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.MentionableSelectComponentForMessageRequest = new global::Soenneker.Discord.OpenApiClient.Models.MentionableSelectComponentForMessageRequest();
                }
                else if("RoleSelectComponentForMessageRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.RoleSelectComponentForMessageRequest = new global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentForMessageRequest();
                }
                else if("StringSelectComponentForMessageRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.StringSelectComponentForMessageRequest = new global::Soenneker.Discord.OpenApiClient.Models.StringSelectComponentForMessageRequest();
                }
                else if("UserSelectComponentForMessageRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserSelectComponentForMessageRequest = new global::Soenneker.Discord.OpenApiClient.Models.UserSelectComponentForMessageRequest();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ButtonComponentForMessageRequest != null)
                {
                    return ButtonComponentForMessageRequest.GetFieldDeserializers();
                }
                else if(ChannelSelectComponentForMessageRequest != null)
                {
                    return ChannelSelectComponentForMessageRequest.GetFieldDeserializers();
                }
                else if(MentionableSelectComponentForMessageRequest != null)
                {
                    return MentionableSelectComponentForMessageRequest.GetFieldDeserializers();
                }
                else if(RoleSelectComponentForMessageRequest != null)
                {
                    return RoleSelectComponentForMessageRequest.GetFieldDeserializers();
                }
                else if(StringSelectComponentForMessageRequest != null)
                {
                    return StringSelectComponentForMessageRequest.GetFieldDeserializers();
                }
                else if(UserSelectComponentForMessageRequest != null)
                {
                    return UserSelectComponentForMessageRequest.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ButtonComponentForMessageRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ButtonComponentForMessageRequest>(null, ButtonComponentForMessageRequest);
                }
                else if(ChannelSelectComponentForMessageRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ChannelSelectComponentForMessageRequest>(null, ChannelSelectComponentForMessageRequest);
                }
                else if(MentionableSelectComponentForMessageRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MentionableSelectComponentForMessageRequest>(null, MentionableSelectComponentForMessageRequest);
                }
                else if(RoleSelectComponentForMessageRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentForMessageRequest>(null, RoleSelectComponentForMessageRequest);
                }
                else if(StringSelectComponentForMessageRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StringSelectComponentForMessageRequest>(null, StringSelectComponentForMessageRequest);
                }
                else if(UserSelectComponentForMessageRequest != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserSelectComponentForMessageRequest>(null, UserSelectComponentForMessageRequest);
                }
            }
        }
    }
}
#pragma warning restore CS0618
