// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse? Bot { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse Bot { get; set; }
#endif
        /// <summary>The bot_public property</summary>
        public bool? BotPublic { get; set; }
        /// <summary>The bot_require_code_grant property</summary>
        public bool? BotRequireCodeGrant { get; set; }
        /// <summary>The cover_image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverImage { get; set; }
#nullable restore
#else
        public string CoverImage { get; set; }
#endif
        /// <summary>The custom_install_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomInstallUrl { get; set; }
#nullable restore
#else
        public string CustomInstallUrl { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The flags property</summary>
        public int? Flags { get; set; }
        /// <summary>The guild_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuildId { get; set; }
#nullable restore
#else
        public string GuildId { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The install_params property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationOAuth2InstallParamsResponse? InstallParams { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationOAuth2InstallParamsResponse InstallParams { get; set; }
#endif
        /// <summary>The integration_types_config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_integration_types_config? IntegrationTypesConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_integration_types_config IntegrationTypesConfig { get; set; }
#endif
        /// <summary>The max_participants property</summary>
        public int? MaxParticipants { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The primary_sku_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimarySkuId { get; set; }
#nullable restore
#else
        public string PrimarySkuId { get; set; }
#endif
        /// <summary>The privacy_policy_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrivacyPolicyUrl { get; set; }
#nullable restore
#else
        public string PrivacyPolicyUrl { get; set; }
#endif
        /// <summary>The rpc_origins property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RpcOrigins { get; set; }
#nullable restore
#else
        public List<string> RpcOrigins { get; set; }
#endif
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The terms_of_service_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TermsOfServiceUrl { get; set; }
#nullable restore
#else
        public string TermsOfServiceUrl { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type Type { get; set; }
#endif
        /// <summary>The verify_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerifyKey { get; set; }
#nullable restore
#else
        public string VerifyKey { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse"/> and sets the default values.
        /// </summary>
        public ApplicationResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bot", n => { Bot = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue); } },
                { "bot_public", n => { BotPublic = n.GetBoolValue(); } },
                { "bot_require_code_grant", n => { BotRequireCodeGrant = n.GetBoolValue(); } },
                { "cover_image", n => { CoverImage = n.GetStringValue(); } },
                { "custom_install_url", n => { CustomInstallUrl = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "flags", n => { Flags = n.GetIntValue(); } },
                { "guild_id", n => { GuildId = n.GetStringValue(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "install_params", n => { InstallParams = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationOAuth2InstallParamsResponse>(global::Soenneker.Discord.OpenApiClient.Models.ApplicationOAuth2InstallParamsResponse.CreateFromDiscriminatorValue); } },
                { "integration_types_config", n => { IntegrationTypesConfig = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_integration_types_config>(global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_integration_types_config.CreateFromDiscriminatorValue); } },
                { "max_participants", n => { MaxParticipants = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "primary_sku_id", n => { PrimarySkuId = n.GetStringValue(); } },
                { "privacy_policy_url", n => { PrivacyPolicyUrl = n.GetStringValue(); } },
                { "rpc_origins", n => { RpcOrigins = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "terms_of_service_url", n => { TermsOfServiceUrl = n.GetStringValue(); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type>(global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type.CreateFromDiscriminatorValue); } },
                { "verify_key", n => { VerifyKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("bot", Bot);
            writer.WriteBoolValue("bot_public", BotPublic);
            writer.WriteBoolValue("bot_require_code_grant", BotRequireCodeGrant);
            writer.WriteStringValue("cover_image", CoverImage);
            writer.WriteStringValue("custom_install_url", CustomInstallUrl);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("flags", Flags);
            writer.WriteStringValue("guild_id", GuildId);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationOAuth2InstallParamsResponse>("install_params", InstallParams);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_integration_types_config>("integration_types_config", IntegrationTypesConfig);
            writer.WriteIntValue("max_participants", MaxParticipants);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("primary_sku_id", PrimarySkuId);
            writer.WriteStringValue("privacy_policy_url", PrivacyPolicyUrl);
            writer.WriteCollectionOfPrimitiveValues<string>("rpc_origins", RpcOrigins);
            writer.WriteStringValue("slug", Slug);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("terms_of_service_url", TermsOfServiceUrl);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type>("type", Type);
            writer.WriteStringValue("verify_key", VerifyKey);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_typeMember1"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApplicationResponse_type : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_typeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_typeMember1? ApplicationResponseTypeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_typeMember1 ApplicationResponseTypeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes? ApplicationTypes { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes ApplicationTypes { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse.ApplicationResponse_type();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ApplicationResponseTypeMember1 = new global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_typeMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ApplicationTypes = new global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ApplicationResponseTypeMember1 != null)
                {
                    return ApplicationResponseTypeMember1.GetFieldDeserializers();
                }
                else if(ApplicationTypes != null)
                {
                    return ApplicationTypes.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ApplicationResponseTypeMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationResponse_typeMember1>(null, ApplicationResponseTypeMember1);
                }
                else if(ApplicationTypes != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes>(null, ApplicationTypes);
                }
            }
        }
    }
}
#pragma warning restore CS0618
