// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationCommandInteractionMetadataResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The authorizing_integration_owners property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse_authorizing_integration_owners? AuthorizingIntegrationOwners { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse_authorizing_integration_owners AuthorizingIntegrationOwners { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The original_response_message_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalResponseMessageId { get; set; }
#nullable restore
#else
        public string OriginalResponseMessageId { get; set; }
#endif
        /// <summary>The target_message_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetMessageId { get; set; }
#nullable restore
#else
        public string TargetMessageId { get; set; }
#endif
        /// <summary>The target_user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse? TargetUser { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse TargetUser { get; set; }
#endif
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse"/> and sets the default values.
        /// </summary>
        public ApplicationCommandInteractionMetadataResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authorizing_integration_owners", n => { AuthorizingIntegrationOwners = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse_authorizing_integration_owners>(global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse_authorizing_integration_owners.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "original_response_message_id", n => { OriginalResponseMessageId = n.GetStringValue(); } },
                { "target_message_id", n => { TargetMessageId = n.GetStringValue(); } },
                { "target_user", n => { TargetUser = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandInteractionMetadataResponse_authorizing_integration_owners>("authorizing_integration_owners", AuthorizingIntegrationOwners);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("original_response_message_id", OriginalResponseMessageId);
            writer.WriteStringValue("target_message_id", TargetMessageId);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("target_user", TargetUser);
            writer.WriteIntValue("type", Type);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
