// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>The hu locale</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AvailableLocalesEnumMember16
    {
        [EnumMember(Value = "hu")]
        #pragma warning disable CS1591
        Hu,
        #pragma warning restore CS1591
    }
}
