// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BasicApplicationResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bot property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse? Bot { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse Bot { get; set; }
#endif
        /// <summary>The cover_image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverImage { get; set; }
#nullable restore
#else
        public string CoverImage { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The primary_sku_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimarySkuId { get; set; }
#nullable restore
#else
        public string PrimarySkuId { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type? Type { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse"/> and sets the default values.
        /// </summary>
        public BasicApplicationResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bot", n => { Bot = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue); } },
                { "cover_image", n => { CoverImage = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "primary_sku_id", n => { PrimarySkuId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type>(global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("bot", Bot);
            writer.WriteStringValue("cover_image", CoverImage);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("primary_sku_id", PrimarySkuId);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse_typeMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BasicApplicationResponse_type : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes? ApplicationTypes { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes ApplicationTypes { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse_typeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse_typeMember1? BasicApplicationResponseTypeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse_typeMember1 BasicApplicationResponseTypeMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse.BasicApplicationResponse_type();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ApplicationTypes = new global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BasicApplicationResponseTypeMember1 = new global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse_typeMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ApplicationTypes != null)
                {
                    return ApplicationTypes.GetFieldDeserializers();
                }
                else if(BasicApplicationResponseTypeMember1 != null)
                {
                    return BasicApplicationResponseTypeMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ApplicationTypes != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationTypes>(null, ApplicationTypes);
                }
                else if(BasicApplicationResponseTypeMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponse_typeMember1>(null, BasicApplicationResponseTypeMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
