// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConnectedAccountProvidersMember13
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "reddit")]
        #pragma warning disable CS1591
        Reddit,
        #pragma warning restore CS1591
    }
}
