// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConnectedAccountProvidersMember21
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "twitter")]
        #pragma warning disable CS1591
        Twitter,
        #pragma warning restore CS1591
    }
}
