// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConnectedAccountResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The friend_sync property</summary>
        public bool? FriendSync { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The integrations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountIntegrationResponse>? Integrations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountIntegrationResponse> Integrations { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The revoked property</summary>
        public bool? Revoked { get; set; }
        /// <summary>The show_activity property</summary>
        public bool? ShowActivity { get; set; }
        /// <summary>The two_way_link property</summary>
        public bool? TwoWayLink { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The verified property</summary>
        public bool? Verified { get; set; }
        /// <summary>The visibility property</summary>
        public int? Visibility { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountResponse"/> and sets the default values.
        /// </summary>
        public ConnectedAccountResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "friend_sync", n => { FriendSync = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "integrations", n => { Integrations = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountIntegrationResponse>(global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountIntegrationResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "revoked", n => { Revoked = n.GetBoolValue(); } },
                { "show_activity", n => { ShowActivity = n.GetBoolValue(); } },
                { "two_way_link", n => { TwoWayLink = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "verified", n => { Verified = n.GetBoolValue(); } },
                { "visibility", n => { Visibility = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("friend_sync", FriendSync);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.ConnectedAccountIntegrationResponse>("integrations", Integrations);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("revoked", Revoked);
            writer.WriteBoolValue("show_activity", ShowActivity);
            writer.WriteBoolValue("two_way_link", TwoWayLink);
            writer.WriteStringValue("type", Type);
            writer.WriteBoolValue("verified", Verified);
            writer.WriteIntValue("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
