// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandAutocompleteCallbackRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.CreateMessageInteractionCallbackRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.LaunchActivityInteractionCallbackRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ModalInteractionCallbackRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.PongInteractionCallbackRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateMessageInteractionCallbackRequest"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateInteractionResponseJsonRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandAutocompleteCallbackRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandAutocompleteCallbackRequest? ApplicationCommandAutocompleteCallbackRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandAutocompleteCallbackRequest ApplicationCommandAutocompleteCallbackRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.CreateMessageInteractionCallbackRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.CreateMessageInteractionCallbackRequest? CreateMessageInteractionCallbackRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.CreateMessageInteractionCallbackRequest CreateMessageInteractionCallbackRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.LaunchActivityInteractionCallbackRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.LaunchActivityInteractionCallbackRequest? LaunchActivityInteractionCallbackRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.LaunchActivityInteractionCallbackRequest LaunchActivityInteractionCallbackRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ModalInteractionCallbackRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ModalInteractionCallbackRequest? ModalInteractionCallbackRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ModalInteractionCallbackRequest ModalInteractionCallbackRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.PongInteractionCallbackRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.PongInteractionCallbackRequest? PongInteractionCallbackRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.PongInteractionCallbackRequest PongInteractionCallbackRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest? SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateMessageInteractionCallbackRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UpdateMessageInteractionCallbackRequest? UpdateMessageInteractionCallbackRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UpdateMessageInteractionCallbackRequest UpdateMessageInteractionCallbackRequest { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.CreateInteractionResponseJsonRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.CreateInteractionResponseJsonRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Discord.OpenApiClient.Models.CreateInteractionResponseJsonRequest();
            result.ApplicationCommandAutocompleteCallbackRequest = new global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandAutocompleteCallbackRequest();
            result.CreateMessageInteractionCallbackRequest = new global::Soenneker.Discord.OpenApiClient.Models.CreateMessageInteractionCallbackRequest();
            result.LaunchActivityInteractionCallbackRequest = new global::Soenneker.Discord.OpenApiClient.Models.LaunchActivityInteractionCallbackRequest();
            result.ModalInteractionCallbackRequest = new global::Soenneker.Discord.OpenApiClient.Models.ModalInteractionCallbackRequest();
            result.PongInteractionCallbackRequest = new global::Soenneker.Discord.OpenApiClient.Models.PongInteractionCallbackRequest();
            result.SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest = new global::Soenneker.Discord.OpenApiClient.Models.SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest();
            result.UpdateMessageInteractionCallbackRequest = new global::Soenneker.Discord.OpenApiClient.Models.UpdateMessageInteractionCallbackRequest();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ApplicationCommandAutocompleteCallbackRequest != null || CreateMessageInteractionCallbackRequest != null || LaunchActivityInteractionCallbackRequest != null || ModalInteractionCallbackRequest != null || PongInteractionCallbackRequest != null || SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest != null || UpdateMessageInteractionCallbackRequest != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ApplicationCommandAutocompleteCallbackRequest, CreateMessageInteractionCallbackRequest, LaunchActivityInteractionCallbackRequest, ModalInteractionCallbackRequest, PongInteractionCallbackRequest, SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest, UpdateMessageInteractionCallbackRequest);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ApplicationCommandAutocompleteCallbackRequest>(null, ApplicationCommandAutocompleteCallbackRequest, CreateMessageInteractionCallbackRequest, LaunchActivityInteractionCallbackRequest, ModalInteractionCallbackRequest, PongInteractionCallbackRequest, SocialLayerSkuPurchaseEligibilityInteractionCallbackRequest, UpdateMessageInteractionCallbackRequest);
        }
    }
}
#pragma warning restore CS0618
