// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExternalConnectionIntegrationResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The account property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.AccountResponse? Account { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.AccountResponse Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The enable_emoticons property</summary>
        public bool? EnableEmoticons { get; set; }
        /// <summary>The expire_behavior property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireBehaviorTypes? ExpireBehavior { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireBehaviorTypes ExpireBehavior { get; set; }
#endif
        /// <summary>The expire_grace_period property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireGracePeriodTypes? ExpireGracePeriod { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireGracePeriodTypes ExpireGracePeriod { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The revoked property</summary>
        public bool? Revoked { get; set; }
        /// <summary>The role_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoleId { get; set; }
#nullable restore
#else
        public string RoleId { get; set; }
#endif
        /// <summary>The subscriber_count property</summary>
        public int? SubscriberCount { get; set; }
        /// <summary>The synced_at property</summary>
        public DateTimeOffset? SyncedAt { get; set; }
        /// <summary>The syncing property</summary>
        public bool? Syncing { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse_type? Type { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse"/> and sets the default values.
        /// </summary>
        public ExternalConnectionIntegrationResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.AccountResponse>(global::Soenneker.Discord.OpenApiClient.Models.AccountResponse.CreateFromDiscriminatorValue); } },
                { "enable_emoticons", n => { EnableEmoticons = n.GetBoolValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "expire_behavior", n => { ExpireBehavior = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireBehaviorTypes>(global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireBehaviorTypes.CreateFromDiscriminatorValue); } },
                { "expire_grace_period", n => { ExpireGracePeriod = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireGracePeriodTypes>(global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireGracePeriodTypes.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "revoked", n => { Revoked = n.GetBoolValue(); } },
                { "role_id", n => { RoleId = n.GetStringValue(); } },
                { "subscriber_count", n => { SubscriberCount = n.GetIntValue(); } },
                { "synced_at", n => { SyncedAt = n.GetDateTimeOffsetValue(); } },
                { "syncing", n => { Syncing = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse_type>(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.AccountResponse>("account", Account);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("enable_emoticons", EnableEmoticons);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireBehaviorTypes>("expire_behavior", ExpireBehavior);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationExpireGracePeriodTypes>("expire_grace_period", ExpireGracePeriod);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("revoked", Revoked);
            writer.WriteStringValue("role_id", RoleId);
            writer.WriteIntValue("subscriber_count", SubscriberCount);
            writer.WriteDateTimeOffsetValue("synced_at", SyncedAt);
            writer.WriteBoolValue("syncing", Syncing);
            writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse_type>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
