// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GuildPatchRequestPartial : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The afk_channel_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AfkChannelId { get; set; }
#nullable restore
#else
        public string AfkChannelId { get; set; }
#endif
        /// <summary>The afk_timeout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.AfkTimeouts_Wrapper? AfkTimeout { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.AfkTimeouts_Wrapper AfkTimeout { get; set; }
#endif
        /// <summary>The banner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Banner { get; set; }
#nullable restore
#else
        public string Banner { get; set; }
#endif
        /// <summary>The default_message_notifications property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserNotificationSettings_Wrapper? DefaultMessageNotifications { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserNotificationSettings_Wrapper DefaultMessageNotifications { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The discovery_splash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DiscoverySplash { get; set; }
#nullable restore
#else
        public string DiscoverySplash { get; set; }
#endif
        /// <summary>The explicit_content_filter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.GuildExplicitContentFilterTypes_Wrapper? ExplicitContentFilter { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.GuildExplicitContentFilterTypes_Wrapper ExplicitContentFilter { get; set; }
#endif
        /// <summary>The features property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Features { get; set; }
#nullable restore
#else
        public List<string> Features { get; set; }
#endif
        /// <summary>The home_header property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HomeHeader { get; set; }
#nullable restore
#else
        public string HomeHeader { get; set; }
#endif
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The preferred_locale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.AvailableLocalesEnum_Wrapper? PreferredLocale { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.AvailableLocalesEnum_Wrapper PreferredLocale { get; set; }
#endif
        /// <summary>The premium_progress_bar_enabled property</summary>
        public bool? PremiumProgressBarEnabled { get; set; }
        /// <summary>The public_updates_channel_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicUpdatesChannelId { get; set; }
#nullable restore
#else
        public string PublicUpdatesChannelId { get; set; }
#endif
        /// <summary>The region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The rules_channel_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RulesChannelId { get; set; }
#nullable restore
#else
        public string RulesChannelId { get; set; }
#endif
        /// <summary>The safety_alerts_channel_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SafetyAlertsChannelId { get; set; }
#nullable restore
#else
        public string SafetyAlertsChannelId { get; set; }
#endif
        /// <summary>The splash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Splash { get; set; }
#nullable restore
#else
        public string Splash { get; set; }
#endif
        /// <summary>The system_channel_flags property</summary>
        public int? SystemChannelFlags { get; set; }
        /// <summary>The system_channel_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SystemChannelId { get; set; }
#nullable restore
#else
        public string SystemChannelId { get; set; }
#endif
        /// <summary>The verification_level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.VerificationLevels_Wrapper? VerificationLevel { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.VerificationLevels_Wrapper VerificationLevel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildPatchRequestPartial"/> and sets the default values.
        /// </summary>
        public GuildPatchRequestPartial()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildPatchRequestPartial"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.GuildPatchRequestPartial CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.GuildPatchRequestPartial();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "afk_channel_id", n => { AfkChannelId = n.GetStringValue(); } },
                { "afk_timeout", n => { AfkTimeout = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.AfkTimeouts_Wrapper>(global::Soenneker.Discord.OpenApiClient.Models.AfkTimeouts_Wrapper.CreateFromDiscriminatorValue); } },
                { "banner", n => { Banner = n.GetStringValue(); } },
                { "default_message_notifications", n => { DefaultMessageNotifications = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserNotificationSettings_Wrapper>(global::Soenneker.Discord.OpenApiClient.Models.UserNotificationSettings_Wrapper.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "discovery_splash", n => { DiscoverySplash = n.GetStringValue(); } },
                { "explicit_content_filter", n => { ExplicitContentFilter = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildExplicitContentFilterTypes_Wrapper>(global::Soenneker.Discord.OpenApiClient.Models.GuildExplicitContentFilterTypes_Wrapper.CreateFromDiscriminatorValue); } },
                { "features", n => { Features = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "home_header", n => { HomeHeader = n.GetStringValue(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "preferred_locale", n => { PreferredLocale = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.AvailableLocalesEnum_Wrapper>(global::Soenneker.Discord.OpenApiClient.Models.AvailableLocalesEnum_Wrapper.CreateFromDiscriminatorValue); } },
                { "premium_progress_bar_enabled", n => { PremiumProgressBarEnabled = n.GetBoolValue(); } },
                { "public_updates_channel_id", n => { PublicUpdatesChannelId = n.GetStringValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "rules_channel_id", n => { RulesChannelId = n.GetStringValue(); } },
                { "safety_alerts_channel_id", n => { SafetyAlertsChannelId = n.GetStringValue(); } },
                { "splash", n => { Splash = n.GetStringValue(); } },
                { "system_channel_flags", n => { SystemChannelFlags = n.GetIntValue(); } },
                { "system_channel_id", n => { SystemChannelId = n.GetStringValue(); } },
                { "verification_level", n => { VerificationLevel = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.VerificationLevels_Wrapper>(global::Soenneker.Discord.OpenApiClient.Models.VerificationLevels_Wrapper.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("afk_channel_id", AfkChannelId);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.AfkTimeouts_Wrapper>("afk_timeout", AfkTimeout);
            writer.WriteStringValue("banner", Banner);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserNotificationSettings_Wrapper>("default_message_notifications", DefaultMessageNotifications);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("discovery_splash", DiscoverySplash);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildExplicitContentFilterTypes_Wrapper>("explicit_content_filter", ExplicitContentFilter);
            writer.WriteCollectionOfPrimitiveValues<string>("features", Features);
            writer.WriteStringValue("home_header", HomeHeader);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.AvailableLocalesEnum_Wrapper>("preferred_locale", PreferredLocale);
            writer.WriteBoolValue("premium_progress_bar_enabled", PremiumProgressBarEnabled);
            writer.WriteStringValue("public_updates_channel_id", PublicUpdatesChannelId);
            writer.WriteStringValue("region", Region);
            writer.WriteStringValue("rules_channel_id", RulesChannelId);
            writer.WriteStringValue("safety_alerts_channel_id", SafetyAlertsChannelId);
            writer.WriteStringValue("splash", Splash);
            writer.WriteIntValue("system_channel_flags", SystemChannelFlags);
            writer.WriteStringValue("system_channel_id", SystemChannelId);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.VerificationLevels_Wrapper>("verification_level", VerificationLevel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
