// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>Applicant started but not yet submitted join request</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GuildJoinRequestApplicationStatusMember1
    {
        [EnumMember(Value = "STARTED")]
        #pragma warning disable CS1591
        Started,
        #pragma warning restore CS1591
    }
}
