// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GuildJoinRequestResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actioned_by_user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseActionedByUser? ActionedByUser { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseActionedByUser ActionedByUser { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The application_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestApplicationStatus? ApplicationStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestApplicationStatus ApplicationStatus { get; set; }
#endif
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Applicant&apos;s responses on join request form</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseFormResponsesItem>? FormResponses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseFormResponsesItem> FormResponses { get; set; }
#endif
        /// <summary>The guild_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuildId { get; set; }
#nullable restore
#else
        public string GuildId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Reason request was rejected. Only set when application_status is REJECTED</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RejectionReason { get; set; }
#nullable restore
#else
        public string RejectionReason { get; set; }
#endif
        /// <summary>The reviewed_at property</summary>
        public DateTimeOffset? ReviewedAt { get; set; }
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseUser? User { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseUser User { get; set; }
#endif
        /// <summary>The user_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponse"/> and sets the default values.
        /// </summary>
        public GuildJoinRequestResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actioned_by_user", n => { ActionedByUser = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseActionedByUser>(global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseActionedByUser.CreateFromDiscriminatorValue); } },
                { "application_status", n => { ApplicationStatus = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestApplicationStatus>(global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestApplicationStatus.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "form_responses", n => { FormResponses = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseFormResponsesItem>(global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseFormResponsesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "guild_id", n => { GuildId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "rejection_reason", n => { RejectionReason = n.GetStringValue(); } },
                { "reviewed_at", n => { ReviewedAt = n.GetDateTimeOffsetValue(); } },
                { "user", n => { User = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseUser>(global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseUser.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseActionedByUser>("actioned_by_user", ActionedByUser);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestApplicationStatus>("application_status", ApplicationStatus);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseFormResponsesItem>("form_responses", FormResponses);
            writer.WriteStringValue("guild_id", GuildId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("rejection_reason", RejectionReason);
            writer.WriteDateTimeOffsetValue("reviewed_at", ReviewedAt);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildJoinRequestResponseUser>("user", User);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
