// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember1"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember2"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember3"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember4"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntegrationTypes : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember1"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember1? IntegrationTypesMember1 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember2"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember2? IntegrationTypesMember2 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember3"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember3? IntegrationTypesMember3 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember4"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember4? IntegrationTypesMember4 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypes();
            if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember1>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember1 integrationTypesMember1Value)
            {
                result.IntegrationTypesMember1 = integrationTypesMember1Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember2>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember2 integrationTypesMember2Value)
            {
                result.IntegrationTypesMember2 = integrationTypesMember2Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember3>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember3 integrationTypesMember3Value)
            {
                result.IntegrationTypesMember3 = integrationTypesMember3Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember4>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember4 integrationTypesMember4Value)
            {
                result.IntegrationTypesMember4 = integrationTypesMember4Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(IntegrationTypesMember1 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember1>(null, IntegrationTypesMember1);
            }
            else if(IntegrationTypesMember2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember2>(null, IntegrationTypesMember2);
            }
            else if(IntegrationTypesMember3 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember3>(null, IntegrationTypesMember3);
            }
            else if(IntegrationTypesMember4 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesMember4>(null, IntegrationTypesMember4);
            }
        }
    }
}
#pragma warning restore CS0618
