// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf1"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf2"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf3"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf4"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IntegrationTypes : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf1"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf1? IntegrationTypesOneOf1 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf2"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf2? IntegrationTypesOneOf2 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf3"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf3? IntegrationTypesOneOf3 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf4"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf4? IntegrationTypesOneOf4 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypes"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypes CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypes();
            if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf1>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf1 integrationTypesOneOf1Value)
            {
                result.IntegrationTypesOneOf1 = integrationTypesOneOf1Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf2>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf2 integrationTypesOneOf2Value)
            {
                result.IntegrationTypesOneOf2 = integrationTypesOneOf2Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf3>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf3 integrationTypesOneOf3Value)
            {
                result.IntegrationTypesOneOf3 = integrationTypesOneOf3Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf4>() is global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf4 integrationTypesOneOf4Value)
            {
                result.IntegrationTypesOneOf4 = integrationTypesOneOf4Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(IntegrationTypesOneOf1 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf1>(null, IntegrationTypesOneOf1);
            }
            else if(IntegrationTypesOneOf2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf2>(null, IntegrationTypesOneOf2);
            }
            else if(IntegrationTypesOneOf3 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf3>(null, IntegrationTypesOneOf3);
            }
            else if(IntegrationTypesOneOf4 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.IntegrationTypesOneOf4>(null, IntegrationTypesOneOf4);
            }
        }
    }
}
#pragma warning restore CS0618
