// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.DiscordIntegrationResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildSubscriptionIntegrationResponse"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListGuildIntegrations200ResponseItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.DiscordIntegrationResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.DiscordIntegrationResponse? DiscordIntegrationResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.DiscordIntegrationResponse DiscordIntegrationResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse? ExternalConnectionIntegrationResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse ExternalConnectionIntegrationResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildSubscriptionIntegrationResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.GuildSubscriptionIntegrationResponse? GuildSubscriptionIntegrationResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.GuildSubscriptionIntegrationResponse GuildSubscriptionIntegrationResponse { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ListGuildIntegrations200ResponseItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ListGuildIntegrations200ResponseItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Discord.OpenApiClient.Models.ListGuildIntegrations200ResponseItem();
            if("DiscordIntegrationResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DiscordIntegrationResponse = new global::Soenneker.Discord.OpenApiClient.Models.DiscordIntegrationResponse();
            }
            else if("ExternalConnectionIntegrationResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ExternalConnectionIntegrationResponse = new global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse();
            }
            else if("GuildSubscriptionIntegrationResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.GuildSubscriptionIntegrationResponse = new global::Soenneker.Discord.OpenApiClient.Models.GuildSubscriptionIntegrationResponse();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DiscordIntegrationResponse != null)
            {
                return DiscordIntegrationResponse.GetFieldDeserializers();
            }
            else if(ExternalConnectionIntegrationResponse != null)
            {
                return ExternalConnectionIntegrationResponse.GetFieldDeserializers();
            }
            else if(GuildSubscriptionIntegrationResponse != null)
            {
                return GuildSubscriptionIntegrationResponse.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DiscordIntegrationResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.DiscordIntegrationResponse>(null, DiscordIntegrationResponse);
            }
            else if(ExternalConnectionIntegrationResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ExternalConnectionIntegrationResponse>(null, ExternalConnectionIntegrationResponse);
            }
            else if(GuildSubscriptionIntegrationResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildSubscriptionIntegrationResponse>(null, GuildSubscriptionIntegrationResponse);
            }
        }
    }
}
#pragma warning restore CS0618
