// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.DefaultKeywordRuleResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.KeywordRuleResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.MentionSpamRuleResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.MlSpamRuleResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserProfileRuleResponse"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListAutoModerationRules200ResponseItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.DefaultKeywordRuleResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.DefaultKeywordRuleResponse? DefaultKeywordRuleResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.DefaultKeywordRuleResponse DefaultKeywordRuleResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.KeywordRuleResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.KeywordRuleResponse? KeywordRuleResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.KeywordRuleResponse KeywordRuleResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.MentionSpamRuleResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MentionSpamRuleResponse? MentionSpamRuleResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MentionSpamRuleResponse MentionSpamRuleResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.MlSpamRuleResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MlSpamRuleResponse? MlSpamRuleResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MlSpamRuleResponse MlSpamRuleResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserProfileRuleResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserProfileRuleResponse? UserProfileRuleResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserProfileRuleResponse UserProfileRuleResponse { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ListAutoModerationRules200ResponseItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ListAutoModerationRules200ResponseItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Discord.OpenApiClient.Models.ListAutoModerationRules200ResponseItem();
            if("DefaultKeywordRuleResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DefaultKeywordRuleResponse = new global::Soenneker.Discord.OpenApiClient.Models.DefaultKeywordRuleResponse();
            }
            else if("KeywordRuleResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.KeywordRuleResponse = new global::Soenneker.Discord.OpenApiClient.Models.KeywordRuleResponse();
            }
            else if("MentionSpamRuleResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MentionSpamRuleResponse = new global::Soenneker.Discord.OpenApiClient.Models.MentionSpamRuleResponse();
            }
            else if("MlSpamRuleResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MlSpamRuleResponse = new global::Soenneker.Discord.OpenApiClient.Models.MlSpamRuleResponse();
            }
            else if("UserProfileRuleResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserProfileRuleResponse = new global::Soenneker.Discord.OpenApiClient.Models.UserProfileRuleResponse();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(DefaultKeywordRuleResponse != null)
            {
                return DefaultKeywordRuleResponse.GetFieldDeserializers();
            }
            else if(KeywordRuleResponse != null)
            {
                return KeywordRuleResponse.GetFieldDeserializers();
            }
            else if(MentionSpamRuleResponse != null)
            {
                return MentionSpamRuleResponse.GetFieldDeserializers();
            }
            else if(MlSpamRuleResponse != null)
            {
                return MlSpamRuleResponse.GetFieldDeserializers();
            }
            else if(UserProfileRuleResponse != null)
            {
                return UserProfileRuleResponse.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(DefaultKeywordRuleResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.DefaultKeywordRuleResponse>(null, DefaultKeywordRuleResponse);
            }
            else if(KeywordRuleResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.KeywordRuleResponse>(null, KeywordRuleResponse);
            }
            else if(MentionSpamRuleResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MentionSpamRuleResponse>(null, MentionSpamRuleResponse);
            }
            else if(MlSpamRuleResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MlSpamRuleResponse>(null, MlSpamRuleResponse);
            }
            else if(UserProfileRuleResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserProfileRuleResponse>(null, UserProfileRuleResponse);
            }
        }
    }
}
#pragma warning restore CS0618
