// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MessageResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageActivityResponse? Activity { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageActivityResponse Activity { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The application property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponseWithBot? Application { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponseWithBot Application { get; set; }
#endif
        /// <summary>The application_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApplicationId { get; set; }
#nullable restore
#else
        public string ApplicationId { get; set; }
#endif
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentResponse>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentResponse> Attachments { get; set; }
#endif
        /// <summary>The author property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse? Author { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse Author { get; set; }
#endif
        /// <summary>The call property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCallResponse? Call { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCallResponse Call { get; set; }
#endif
        /// <summary>The channel_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelId { get; set; }
#nullable restore
#else
        public string ChannelId { get; set; }
#endif
        /// <summary>The components property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseComponentsItem>? Components { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseComponentsItem> Components { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>The edited_timestamp property</summary>
        public DateTimeOffset? EditedTimestamp { get; set; }
        /// <summary>The embeds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageEmbedResponse>? Embeds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageEmbedResponse> Embeds { get; set; }
#endif
        /// <summary>The flags property</summary>
        public int? Flags { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The interaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageInteractionResponse? Interaction { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageInteractionResponse Interaction { get; set; }
#endif
        /// <summary>The interaction_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageResponseInteractionMetadata? InteractionMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageResponseInteractionMetadata InteractionMetadata { get; set; }
#endif
        /// <summary>The lobby_member property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageLobbyMemberResponse? LobbyMember { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageLobbyMemberResponse LobbyMember { get; set; }
#endif
        /// <summary>The mention_channels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageMentionChannelResponse>? MentionChannels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageMentionChannelResponse> MentionChannels { get; set; }
#endif
        /// <summary>The mention_everyone property</summary>
        public bool? MentionEveryone { get; set; }
        /// <summary>The mention_roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MentionRoles { get; set; }
#nullable restore
#else
        public List<string> MentionRoles { get; set; }
#endif
        /// <summary>The mentions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>? Mentions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.UserResponse> Mentions { get; set; }
#endif
        /// <summary>The message_reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageReferenceResponse? MessageReference { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageReferenceResponse MessageReference { get; set; }
#endif
        /// <summary>The message_snapshots property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageSnapshotResponse>? MessageSnapshots { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageSnapshotResponse> MessageSnapshots { get; set; }
#endif
        /// <summary>The nonce property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageResponseNonce? Nonce { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageResponseNonce Nonce { get; set; }
#endif
        /// <summary>The pinned property</summary>
        public bool? Pinned { get; set; }
        /// <summary>The poll property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.PollResponse? Poll { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.PollResponse Poll { get; set; }
#endif
        /// <summary>The position property</summary>
        public int? Position { get; set; }
        /// <summary>The purchase_notification property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.PurchaseNotificationResponse? PurchaseNotification { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.PurchaseNotificationResponse PurchaseNotification { get; set; }
#endif
        /// <summary>The reactions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageReactionResponse>? Reactions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageReactionResponse> Reactions { get; set; }
#endif
        /// <summary>The referenced_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageResponseReferencedMessage? ReferencedMessage { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageResponseReferencedMessage ReferencedMessage { get; set; }
#endif
        /// <summary>The resolved property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ResolvedObjectsResponse? Resolved { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ResolvedObjectsResponse Resolved { get; set; }
#endif
        /// <summary>The role_subscription_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageRoleSubscriptionDataResponse? RoleSubscriptionData { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageRoleSubscriptionDataResponse RoleSubscriptionData { get; set; }
#endif
        /// <summary>The shared_client_theme property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.CustomClientThemeResponse? SharedClientTheme { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.CustomClientThemeResponse SharedClientTheme { get; set; }
#endif
        /// <summary>The sticker_items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageStickerItemResponse>? StickerItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageStickerItemResponse> StickerItems { get; set; }
#endif
        /// <summary>The stickers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseStickersItem>? Stickers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseStickersItem> Stickers { get; set; }
#endif
        /// <summary>The thread property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse? Thread { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse Thread { get; set; }
#endif
        /// <summary>The timestamp property</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>The tts property</summary>
        public bool? Tts { get; set; }
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>The webhook_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebhookId { get; set; }
#nullable restore
#else
        public string WebhookId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.MessageResponse"/> and sets the default values.
        /// </summary>
        public MessageResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.MessageResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.MessageResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.MessageResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity", n => { Activity = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageActivityResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageActivityResponse.CreateFromDiscriminatorValue); } },
                { "application", n => { Application = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponseWithBot>(global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponseWithBot.CreateFromDiscriminatorValue); } },
                { "application_id", n => { ApplicationId = n.GetStringValue(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "author", n => { Author = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue); } },
                { "call", n => { Call = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCallResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageCallResponse.CreateFromDiscriminatorValue); } },
                { "channel_id", n => { ChannelId = n.GetStringValue(); } },
                { "components", n => { Components = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseComponentsItem>(global::Soenneker.Discord.OpenApiClient.Models.MessageResponseComponentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "edited_timestamp", n => { EditedTimestamp = n.GetDateTimeOffsetValue(); } },
                { "embeds", n => { Embeds = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageEmbedResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageEmbedResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "flags", n => { Flags = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "interaction", n => { Interaction = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageInteractionResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageInteractionResponse.CreateFromDiscriminatorValue); } },
                { "interaction_metadata", n => { InteractionMetadata = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseInteractionMetadata>(global::Soenneker.Discord.OpenApiClient.Models.MessageResponseInteractionMetadata.CreateFromDiscriminatorValue); } },
                { "lobby_member", n => { LobbyMember = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageLobbyMemberResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageLobbyMemberResponse.CreateFromDiscriminatorValue); } },
                { "mention_channels", n => { MentionChannels = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageMentionChannelResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageMentionChannelResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mention_everyone", n => { MentionEveryone = n.GetBoolValue(); } },
                { "mention_roles", n => { MentionRoles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "mentions", n => { Mentions = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "message_reference", n => { MessageReference = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageReferenceResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageReferenceResponse.CreateFromDiscriminatorValue); } },
                { "message_snapshots", n => { MessageSnapshots = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageSnapshotResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageSnapshotResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nonce", n => { Nonce = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseNonce>(global::Soenneker.Discord.OpenApiClient.Models.MessageResponseNonce.CreateFromDiscriminatorValue); } },
                { "pinned", n => { Pinned = n.GetBoolValue(); } },
                { "poll", n => { Poll = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PollResponse>(global::Soenneker.Discord.OpenApiClient.Models.PollResponse.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "purchase_notification", n => { PurchaseNotification = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PurchaseNotificationResponse>(global::Soenneker.Discord.OpenApiClient.Models.PurchaseNotificationResponse.CreateFromDiscriminatorValue); } },
                { "reactions", n => { Reactions = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageReactionResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageReactionResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "referenced_message", n => { ReferencedMessage = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseReferencedMessage>(global::Soenneker.Discord.OpenApiClient.Models.MessageResponseReferencedMessage.CreateFromDiscriminatorValue); } },
                { "resolved", n => { Resolved = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ResolvedObjectsResponse>(global::Soenneker.Discord.OpenApiClient.Models.ResolvedObjectsResponse.CreateFromDiscriminatorValue); } },
                { "role_subscription_data", n => { RoleSubscriptionData = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageRoleSubscriptionDataResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageRoleSubscriptionDataResponse.CreateFromDiscriminatorValue); } },
                { "shared_client_theme", n => { SharedClientTheme = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.CustomClientThemeResponse>(global::Soenneker.Discord.OpenApiClient.Models.CustomClientThemeResponse.CreateFromDiscriminatorValue); } },
                { "sticker_items", n => { StickerItems = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageStickerItemResponse>(global::Soenneker.Discord.OpenApiClient.Models.MessageStickerItemResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "stickers", n => { Stickers = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseStickersItem>(global::Soenneker.Discord.OpenApiClient.Models.MessageResponseStickersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "thread", n => { Thread = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse>(global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse.CreateFromDiscriminatorValue); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
                { "tts", n => { Tts = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "webhook_id", n => { WebhookId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageActivityResponse>("activity", Activity);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.BasicApplicationResponseWithBot>("application", Application);
            writer.WriteStringValue("application_id", ApplicationId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentResponse>("attachments", Attachments);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("author", Author);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCallResponse>("call", Call);
            writer.WriteStringValue("channel_id", ChannelId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseComponentsItem>("components", Components);
            writer.WriteStringValue("content", Content);
            writer.WriteDateTimeOffsetValue("edited_timestamp", EditedTimestamp);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageEmbedResponse>("embeds", Embeds);
            writer.WriteIntValue("flags", Flags);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageInteractionResponse>("interaction", Interaction);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseInteractionMetadata>("interaction_metadata", InteractionMetadata);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageLobbyMemberResponse>("lobby_member", LobbyMember);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageMentionChannelResponse>("mention_channels", MentionChannels);
            writer.WriteBoolValue("mention_everyone", MentionEveryone);
            writer.WriteCollectionOfPrimitiveValues<string>("mention_roles", MentionRoles);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("mentions", Mentions);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageReferenceResponse>("message_reference", MessageReference);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageSnapshotResponse>("message_snapshots", MessageSnapshots);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseNonce>("nonce", Nonce);
            writer.WriteBoolValue("pinned", Pinned);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PollResponse>("poll", Poll);
            writer.WriteIntValue("position", Position);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PurchaseNotificationResponse>("purchase_notification", PurchaseNotification);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageReactionResponse>("reactions", Reactions);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseReferencedMessage>("referenced_message", ReferencedMessage);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ResolvedObjectsResponse>("resolved", Resolved);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageRoleSubscriptionDataResponse>("role_subscription_data", RoleSubscriptionData);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.CustomClientThemeResponse>("shared_client_theme", SharedClientTheme);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageStickerItemResponse>("sticker_items", StickerItems);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageResponseStickersItem>("stickers", Stickers);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse>("thread", Thread);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteBoolValue("tts", Tts);
            writer.WriteIntValue("type", Type);
            writer.WriteStringValue("webhook_id", WebhookId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
