// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MessageCreateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The allowed_mentions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestAllowedMentions? AllowedMentions { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestAllowedMentions AllowedMentions { get; set; }
#endif
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentRequest>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentRequest> Attachments { get; set; }
#endif
        /// <summary>The components property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestComponentsItem>? Components { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestComponentsItem> Components { get; set; }
#endif
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>The embeds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.RichEmbed>? Embeds { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.RichEmbed> Embeds { get; set; }
#endif
        /// <summary>The enforce_nonce property</summary>
        public bool? EnforceNonce { get; set; }
        /// <summary>The flags property</summary>
        public int? Flags { get; set; }
        /// <summary>The message_reference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestMessageReference? MessageReference { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestMessageReference MessageReference { get; set; }
#endif
        /// <summary>The nonce property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestNonce? Nonce { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestNonce Nonce { get; set; }
#endif
        /// <summary>The poll property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestPoll? Poll { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestPoll Poll { get; set; }
#endif
        /// <summary>The shared_client_theme property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestSharedClientTheme? SharedClientTheme { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestSharedClientTheme SharedClientTheme { get; set; }
#endif
        /// <summary>The sticker_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StickerIds { get; set; }
#nullable restore
#else
        public List<string> StickerIds { get; set; }
#endif
        /// <summary>The tts property</summary>
        public bool? Tts { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequest"/> and sets the default values.
        /// </summary>
        public MessageCreateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_mentions", n => { AllowedMentions = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestAllowedMentions>(global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestAllowedMentions.CreateFromDiscriminatorValue); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentRequest>(global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "components", n => { Components = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestComponentsItem>(global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestComponentsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "embeds", n => { Embeds = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.RichEmbed>(global::Soenneker.Discord.OpenApiClient.Models.RichEmbed.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enforce_nonce", n => { EnforceNonce = n.GetBoolValue(); } },
                { "flags", n => { Flags = n.GetIntValue(); } },
                { "message_reference", n => { MessageReference = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestMessageReference>(global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestMessageReference.CreateFromDiscriminatorValue); } },
                { "nonce", n => { Nonce = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestNonce>(global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestNonce.CreateFromDiscriminatorValue); } },
                { "poll", n => { Poll = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestPoll>(global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestPoll.CreateFromDiscriminatorValue); } },
                { "shared_client_theme", n => { SharedClientTheme = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestSharedClientTheme>(global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestSharedClientTheme.CreateFromDiscriminatorValue); } },
                { "sticker_ids", n => { StickerIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "tts", n => { Tts = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestAllowedMentions>("allowed_mentions", AllowedMentions);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageAttachmentRequest>("attachments", Attachments);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestComponentsItem>("components", Components);
            writer.WriteStringValue("content", Content);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.RichEmbed>("embeds", Embeds);
            writer.WriteBoolValue("enforce_nonce", EnforceNonce);
            writer.WriteIntValue("flags", Flags);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestMessageReference>("message_reference", MessageReference);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestNonce>("nonce", Nonce);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestPoll>("poll", Poll);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MessageCreateRequestSharedClientTheme>("shared_client_theme", SharedClientTheme);
            writer.WriteCollectionOfPrimitiveValues<string>("sticker_ids", StickerIds);
            writer.WriteBoolValue("tts", Tts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
