// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MLSpamRuleResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions>? Actions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions> Actions { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creator_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The event_type property</summary>
        public int? EventType { get; set; }
        /// <summary>The exempt_channels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExemptChannels { get; set; }
#nullable restore
#else
        public List<string> ExemptChannels { get; set; }
#endif
        /// <summary>The exempt_roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExemptRoles { get; set; }
#nullable restore
#else
        public List<string> ExemptRoles { get; set; }
#endif
        /// <summary>The guild_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuildId { get; set; }
#nullable restore
#else
        public string GuildId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The trigger_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.MLSpamTriggerMetadataResponse? TriggerMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.MLSpamTriggerMetadataResponse TriggerMetadata { get; set; }
#endif
        /// <summary>The trigger_type property</summary>
        public int? TriggerType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse"/> and sets the default values.
        /// </summary>
        public MLSpamRuleResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions>(global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "event_type", n => { EventType = n.GetIntValue(); } },
                { "exempt_channels", n => { ExemptChannels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "exempt_roles", n => { ExemptRoles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "guild_id", n => { GuildId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "trigger_metadata", n => { TriggerMetadata = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MLSpamTriggerMetadataResponse>(global::Soenneker.Discord.OpenApiClient.Models.MLSpamTriggerMetadataResponse.CreateFromDiscriminatorValue); } },
                { "trigger_type", n => { TriggerType = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions>("actions", Actions);
            writer.WriteStringValue("creator_id", CreatorId);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteIntValue("event_type", EventType);
            writer.WriteCollectionOfPrimitiveValues<string>("exempt_channels", ExemptChannels);
            writer.WriteCollectionOfPrimitiveValues<string>("exempt_roles", ExemptRoles);
            writer.WriteStringValue("guild_id", GuildId);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.MLSpamTriggerMetadataResponse>("trigger_metadata", TriggerMetadata);
            writer.WriteIntValue("trigger_type", TriggerType);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.BlockMessageActionResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.FlagToChannelActionResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.QuarantineUserActionResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserCommunicationDisabledActionResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MLSpamRuleResponse_actions : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.BlockMessageActionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.BlockMessageActionResponse? BlockMessageActionResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.BlockMessageActionResponse BlockMessageActionResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.FlagToChannelActionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.FlagToChannelActionResponse? FlagToChannelActionResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.FlagToChannelActionResponse FlagToChannelActionResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.QuarantineUserActionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.QuarantineUserActionResponse? QuarantineUserActionResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.QuarantineUserActionResponse QuarantineUserActionResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserCommunicationDisabledActionResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserCommunicationDisabledActionResponse? UserCommunicationDisabledActionResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserCommunicationDisabledActionResponse UserCommunicationDisabledActionResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.MLSpamRuleResponse.MLSpamRuleResponse_actions();
                if("BlockMessageActionResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.BlockMessageActionResponse = new global::Soenneker.Discord.OpenApiClient.Models.BlockMessageActionResponse();
                }
                else if("FlagToChannelActionResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.FlagToChannelActionResponse = new global::Soenneker.Discord.OpenApiClient.Models.FlagToChannelActionResponse();
                }
                else if("QuarantineUserActionResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.QuarantineUserActionResponse = new global::Soenneker.Discord.OpenApiClient.Models.QuarantineUserActionResponse();
                }
                else if("UserCommunicationDisabledActionResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserCommunicationDisabledActionResponse = new global::Soenneker.Discord.OpenApiClient.Models.UserCommunicationDisabledActionResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BlockMessageActionResponse != null)
                {
                    return BlockMessageActionResponse.GetFieldDeserializers();
                }
                else if(FlagToChannelActionResponse != null)
                {
                    return FlagToChannelActionResponse.GetFieldDeserializers();
                }
                else if(QuarantineUserActionResponse != null)
                {
                    return QuarantineUserActionResponse.GetFieldDeserializers();
                }
                else if(UserCommunicationDisabledActionResponse != null)
                {
                    return UserCommunicationDisabledActionResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(BlockMessageActionResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.BlockMessageActionResponse>(null, BlockMessageActionResponse);
                }
                else if(FlagToChannelActionResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.FlagToChannelActionResponse>(null, FlagToChannelActionResponse);
                }
                else if(QuarantineUserActionResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.QuarantineUserActionResponse>(null, QuarantineUserActionResponse);
                }
                else if(UserCommunicationDisabledActionResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserCommunicationDisabledActionResponse>(null, UserCommunicationDisabledActionResponse);
                }
            }
        }
    }
}
#pragma warning restore CS0618
