// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>Type of form field</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ParagraphFormFieldResponse_field_type
    {
        [EnumMember(Value = "PARAGRAPH")]
        #pragma warning disable CS1591
        PARAGRAPH,
        #pragma warning restore CS1591
    }
}
