// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RoleSelectComponentResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The custom_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomId { get; set; }
#nullable restore
#else
        public string CustomId { get; set; }
#endif
        /// <summary>The default_values property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.RoleSelectDefaultValueResponse>? DefaultValues { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.RoleSelectDefaultValueResponse> DefaultValues { get; set; }
#endif
        /// <summary>The disabled property</summary>
        public bool? Disabled { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The max_values property</summary>
        public int? MaxValues { get; set; }
        /// <summary>The min_values property</summary>
        public int? MinValues { get; set; }
        /// <summary>The placeholder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Placeholder { get; set; }
#nullable restore
#else
        public string Placeholder { get; set; }
#endif
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentResponse"/> and sets the default values.
        /// </summary>
        public RoleSelectComponentResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.RoleSelectComponentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_id", n => { CustomId = n.GetStringValue(); } },
                { "default_values", n => { DefaultValues = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.RoleSelectDefaultValueResponse>(global::Soenneker.Discord.OpenApiClient.Models.RoleSelectDefaultValueResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "disabled", n => { Disabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "max_values", n => { MaxValues = n.GetIntValue(); } },
                { "min_values", n => { MinValues = n.GetIntValue(); } },
                { "placeholder", n => { Placeholder = n.GetStringValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("custom_id", CustomId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.RoleSelectDefaultValueResponse>("default_values", DefaultValues);
            writer.WriteBoolValue("disabled", Disabled);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("max_values", MaxValues);
            writer.WriteIntValue("min_values", MinValues);
            writer.WriteStringValue("placeholder", Placeholder);
            writer.WriteIntValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
