// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ScheduledEventUserCountResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The number of users subscribed to the scheduled event</summary>
        public int? GuildScheduledEventCount { get; set; }
        /// <summary>Map of exception IDs to user counts for each exception</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponseGuildScheduledEventExceptionCountsProperty? GuildScheduledEventExceptionCounts { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponseGuildScheduledEventExceptionCountsProperty GuildScheduledEventExceptionCounts { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponse"/> and sets the default values.
        /// </summary>
        public ScheduledEventUserCountResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "guild_scheduled_event_count", n => { GuildScheduledEventCount = n.GetIntValue(); } },
                { "guild_scheduled_event_exception_counts", n => { GuildScheduledEventExceptionCounts = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponseGuildScheduledEventExceptionCountsProperty>(global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponseGuildScheduledEventExceptionCountsProperty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("guild_scheduled_event_count", GuildScheduledEventCount);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ScheduledEventUserCountResponseGuildScheduledEventExceptionCountsProperty>("guild_scheduled_event_exception_counts", GuildScheduledEventExceptionCounts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
