// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StageScheduledEventResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Channel ID in which the scheduled event will be hosted, or null if entity type is EXTERNAL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelId { get; set; }
#nullable restore
#else
        public string ChannelId { get; set; }
#endif
        /// <summary>The creator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse? Creator { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserResponse Creator { get; set; }
#endif
        /// <summary>ID of the user that created the scheduled event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorId { get; set; }
#nullable restore
#else
        public string CreatorId { get; set; }
#endif
        /// <summary>Description of the scheduled event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>ID of the hosting entity associated with the scheduled event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntityId { get; set; }
#nullable restore
#else
        public string EntityId { get; set; }
#endif
        /// <summary>The entity_metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseEntityMetadata? EntityMetadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseEntityMetadata EntityMetadata { get; set; }
#endif
        /// <summary>Type of hosting entity associated with the scheduled event</summary>
        public int? EntityType { get; set; }
        /// <summary>The guild_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GuildId { get; set; }
#nullable restore
#else
        public string GuildId { get; set; }
#endif
        /// <summary>The guild_scheduled_event_exceptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Discord.OpenApiClient.Models.GuildScheduledEventExceptionResponse>? GuildScheduledEventExceptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Discord.OpenApiClient.Models.GuildScheduledEventExceptionResponse> GuildScheduledEventExceptions { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Cover image hash of the scheduled event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image { get; set; }
#nullable restore
#else
        public string Image { get; set; }
#endif
        /// <summary>Name of the scheduled event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The privacy_level property</summary>
        public int? PrivacyLevel { get; set; }
        /// <summary>Recurrence rule for the scheduled event, or null if not recurring</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseRecurrenceRule? RecurrenceRule { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseRecurrenceRule RecurrenceRule { get; set; }
#endif
        /// <summary>When the scheduled event will end, or null if no end time</summary>
        public DateTimeOffset? ScheduledEndTime { get; set; }
        /// <summary>When the scheduled event will start</summary>
        public DateTimeOffset? ScheduledStartTime { get; set; }
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>Number of users subscribed to the scheduled event</summary>
        public int? UserCount { get; set; }
        /// <summary>The user_rsvp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseUserRsvp? UserRsvp { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseUserRsvp UserRsvp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponse"/> and sets the default values.
        /// </summary>
        public StageScheduledEventResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "channel_id", n => { ChannelId = n.GetStringValue(); } },
                { "creator", n => { Creator = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>(global::Soenneker.Discord.OpenApiClient.Models.UserResponse.CreateFromDiscriminatorValue); } },
                { "creator_id", n => { CreatorId = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "entity_id", n => { EntityId = n.GetStringValue(); } },
                { "entity_metadata", n => { EntityMetadata = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseEntityMetadata>(global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseEntityMetadata.CreateFromDiscriminatorValue); } },
                { "entity_type", n => { EntityType = n.GetIntValue(); } },
                { "guild_id", n => { GuildId = n.GetStringValue(); } },
                { "guild_scheduled_event_exceptions", n => { GuildScheduledEventExceptions = n.GetCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.GuildScheduledEventExceptionResponse>(global::Soenneker.Discord.OpenApiClient.Models.GuildScheduledEventExceptionResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image", n => { Image = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "privacy_level", n => { PrivacyLevel = n.GetIntValue(); } },
                { "recurrence_rule", n => { RecurrenceRule = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseRecurrenceRule>(global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseRecurrenceRule.CreateFromDiscriminatorValue); } },
                { "scheduled_end_time", n => { ScheduledEndTime = n.GetDateTimeOffsetValue(); } },
                { "scheduled_start_time", n => { ScheduledStartTime = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "user_count", n => { UserCount = n.GetIntValue(); } },
                { "user_rsvp", n => { UserRsvp = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseUserRsvp>(global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseUserRsvp.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("channel_id", ChannelId);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserResponse>("creator", Creator);
            writer.WriteStringValue("creator_id", CreatorId);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("entity_id", EntityId);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseEntityMetadata>("entity_metadata", EntityMetadata);
            writer.WriteIntValue("entity_type", EntityType);
            writer.WriteStringValue("guild_id", GuildId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Discord.OpenApiClient.Models.GuildScheduledEventExceptionResponse>("guild_scheduled_event_exceptions", GuildScheduledEventExceptions);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("image", Image);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("privacy_level", PrivacyLevel);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseRecurrenceRule>("recurrence_rule", RecurrenceRule);
            writer.WriteDateTimeOffsetValue("scheduled_end_time", ScheduledEndTime);
            writer.WriteDateTimeOffsetValue("scheduled_start_time", ScheduledStartTime);
            writer.WriteIntValue("status", Status);
            writer.WriteIntValue("user_count", UserCount);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StageScheduledEventResponseUserRsvp>("user_rsvp", UserRsvp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
