// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.ComponentEmojiForRequest"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmojiMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StringSelectOptionForRequestEmoji : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ComponentEmojiForRequest"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.ComponentEmojiForRequest? ComponentEmojiForRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.ComponentEmojiForRequest ComponentEmojiForRequest { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmojiMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmojiMember1? StringSelectOptionForRequestEmojiMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmojiMember1 StringSelectOptionForRequestEmojiMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmoji"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmoji CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmoji();
            if("ComponentEmojiForRequest".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ComponentEmojiForRequest = new global::Soenneker.Discord.OpenApiClient.Models.ComponentEmojiForRequest();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ComponentEmojiForRequest != null)
            {
                return ComponentEmojiForRequest.GetFieldDeserializers();
            }
            else if(StringSelectOptionForRequestEmojiMember1 != null)
            {
                return StringSelectOptionForRequestEmojiMember1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ComponentEmojiForRequest != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ComponentEmojiForRequest>(null, ComponentEmojiForRequest);
            }
            else if(StringSelectOptionForRequestEmojiMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.StringSelectOptionForRequestEmojiMember1>(null, StringSelectOptionForRequestEmojiMember1);
            }
        }
    }
}
#pragma warning restore CS0618
