// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>Developers can access information about team-owned apps, like the client secret or public key. They can also take limited actions on team-owned apps, like configuring interaction endpoints or resetting the bot token. Members with the Developer role cannot manage the team or its members, or take destructive actions on team-owned apps.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TeamMemberRolesMember2
    {
        [EnumMember(Value = "developer")]
        #pragma warning disable CS1591
        Developer,
        #pragma warning restore CS1591
    }
}
