// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember1"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ThreadSearchTagSetting : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember1"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember1? ThreadSearchTagSettingMember1 { get; set; }
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember2"/></summary>
        public global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember2? ThreadSearchTagSettingMember2 { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSetting();
            if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember1>() is global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember1 threadSearchTagSettingMember1Value)
            {
                result.ThreadSearchTagSettingMember1 = threadSearchTagSettingMember1Value;
            }
            else if(parseNode.GetEnumValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember2>() is global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember2 threadSearchTagSettingMember2Value)
            {
                result.ThreadSearchTagSettingMember2 = threadSearchTagSettingMember2Value;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ThreadSearchTagSettingMember1 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember1>(null, ThreadSearchTagSettingMember1);
            }
            else if(ThreadSearchTagSettingMember2 != null)
            {
                writer.WriteEnumValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadSearchTagSettingMember2>(null, ThreadSearchTagSettingMember2);
            }
        }
    }
}
#pragma warning restore CS0618
