// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateThreadRequestPartial : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The applied_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AppliedTags { get; set; }
#nullable restore
#else
        public List<string> AppliedTags { get; set; }
#endif
        /// <summary>The archived property</summary>
        public bool? Archived { get; set; }
        /// <summary>The auto_archive_duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration? AutoArchiveDuration { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration AutoArchiveDuration { get; set; }
#endif
        /// <summary>The bitrate property</summary>
        public int? Bitrate { get; set; }
        /// <summary>The flags property</summary>
        public int? Flags { get; set; }
        /// <summary>The invitable property</summary>
        public bool? Invitable { get; set; }
        /// <summary>The locked property</summary>
        public bool? Locked { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The rate_limit_per_user property</summary>
        public int? RateLimitPerUser { get; set; }
        /// <summary>The rtc_region property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RtcRegion { get; set; }
#nullable restore
#else
        public string RtcRegion { get; set; }
#endif
        /// <summary>The user_limit property</summary>
        public int? UserLimit { get; set; }
        /// <summary>The video_quality_mode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode? VideoQualityMode { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode VideoQualityMode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial"/> and sets the default values.
        /// </summary>
        public UpdateThreadRequestPartial()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applied_tags", n => { AppliedTags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "auto_archive_duration", n => { AutoArchiveDuration = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration>(global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration.CreateFromDiscriminatorValue); } },
                { "bitrate", n => { Bitrate = n.GetIntValue(); } },
                { "flags", n => { Flags = n.GetIntValue(); } },
                { "invitable", n => { Invitable = n.GetBoolValue(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "rate_limit_per_user", n => { RateLimitPerUser = n.GetIntValue(); } },
                { "rtc_region", n => { RtcRegion = n.GetStringValue(); } },
                { "user_limit", n => { UserLimit = n.GetIntValue(); } },
                { "video_quality_mode", n => { VideoQualityMode = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode>(global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("applied_tags", AppliedTags);
            writer.WriteBoolValue("archived", Archived);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration>("auto_archive_duration", AutoArchiveDuration);
            writer.WriteIntValue("bitrate", Bitrate);
            writer.WriteIntValue("flags", Flags);
            writer.WriteBoolValue("invitable", Invitable);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("rate_limit_per_user", RateLimitPerUser);
            writer.WriteStringValue("rtc_region", RtcRegion);
            writer.WriteIntValue("user_limit", UserLimit);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode>("video_quality_mode", VideoQualityMode);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadAutoArchiveDuration"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_auto_archive_durationMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateThreadRequestPartial_auto_archive_duration : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadAutoArchiveDuration"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadAutoArchiveDuration? ThreadAutoArchiveDuration { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadAutoArchiveDuration ThreadAutoArchiveDuration { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_auto_archive_durationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_auto_archive_durationMember1? UpdateThreadRequestPartialAutoArchiveDurationMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_auto_archive_durationMember1 UpdateThreadRequestPartialAutoArchiveDurationMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_auto_archive_duration();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ThreadAutoArchiveDuration = new global::Soenneker.Discord.OpenApiClient.Models.ThreadAutoArchiveDuration();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UpdateThreadRequestPartialAutoArchiveDurationMember1 = new global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_auto_archive_durationMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ThreadAutoArchiveDuration != null)
                {
                    return ThreadAutoArchiveDuration.GetFieldDeserializers();
                }
                else if(UpdateThreadRequestPartialAutoArchiveDurationMember1 != null)
                {
                    return UpdateThreadRequestPartialAutoArchiveDurationMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ThreadAutoArchiveDuration != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadAutoArchiveDuration>(null, ThreadAutoArchiveDuration);
                }
                else if(UpdateThreadRequestPartialAutoArchiveDurationMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_auto_archive_durationMember1>(null, UpdateThreadRequestPartialAutoArchiveDurationMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_video_quality_modeMember1"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.VideoQualityModes"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UpdateThreadRequestPartial_video_quality_mode : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_video_quality_modeMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_video_quality_modeMember1? UpdateThreadRequestPartialVideoQualityModeMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_video_quality_modeMember1 UpdateThreadRequestPartialVideoQualityModeMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.VideoQualityModes"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.VideoQualityModes? VideoQualityModes { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.VideoQualityModes VideoQualityModes { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial.UpdateThreadRequestPartial_video_quality_mode();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UpdateThreadRequestPartialVideoQualityModeMember1 = new global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_video_quality_modeMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.VideoQualityModes = new global::Soenneker.Discord.OpenApiClient.Models.VideoQualityModes();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateThreadRequestPartialVideoQualityModeMember1 != null)
                {
                    return UpdateThreadRequestPartialVideoQualityModeMember1.GetFieldDeserializers();
                }
                else if(VideoQualityModes != null)
                {
                    return VideoQualityModes.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(UpdateThreadRequestPartialVideoQualityModeMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial_video_quality_modeMember1>(null, UpdateThreadRequestPartialVideoQualityModeMember1);
                }
                else if(VideoQualityModes != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.VideoQualityModes>(null, VideoQualityModes);
                }
            }
        }
    }
}
#pragma warning restore CS0618
