// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Discord.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserPIIResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accent_color property</summary>
        public int? AccentColor { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The avatar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Avatar { get; set; }
#nullable restore
#else
        public string Avatar { get; set; }
#endif
        /// <summary>The avatar_decoration_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data? AvatarDecorationData { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data AvatarDecorationData { get; set; }
#endif
        /// <summary>The banner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Banner { get; set; }
#nullable restore
#else
        public string Banner { get; set; }
#endif
        /// <summary>The bot property</summary>
        public bool? Bot { get; set; }
        /// <summary>The collectibles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles? Collectibles { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles Collectibles { get; set; }
#endif
        /// <summary>The discriminator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Discriminator { get; set; }
#nullable restore
#else
        public string Discriminator { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The flags property</summary>
        public long? Flags { get; set; }
        /// <summary>The global_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GlobalName { get; set; }
#nullable restore
#else
        public string GlobalName { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The locale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>The mfa_enabled property</summary>
        public bool? MfaEnabled { get; set; }
        /// <summary>The premium_type property</summary>
        public int? PremiumType { get; set; }
        /// <summary>The primary_guild property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild? PrimaryGuild { get; set; }
#nullable restore
#else
        public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild PrimaryGuild { get; set; }
#endif
        /// <summary>The public_flags property</summary>
        public int? PublicFlags { get; set; }
        /// <summary>The system property</summary>
        public bool? System { get; set; }
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>The verified property</summary>
        public bool? Verified { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse"/> and sets the default values.
        /// </summary>
        public UserPIIResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accent_color", n => { AccentColor = n.GetIntValue(); } },
                { "avatar", n => { Avatar = n.GetStringValue(); } },
                { "avatar_decoration_data", n => { AvatarDecorationData = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data>(global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data.CreateFromDiscriminatorValue); } },
                { "banner", n => { Banner = n.GetStringValue(); } },
                { "bot", n => { Bot = n.GetBoolValue(); } },
                { "collectibles", n => { Collectibles = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles>(global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles.CreateFromDiscriminatorValue); } },
                { "discriminator", n => { Discriminator = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "flags", n => { Flags = n.GetLongValue(); } },
                { "global_name", n => { GlobalName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "mfa_enabled", n => { MfaEnabled = n.GetBoolValue(); } },
                { "premium_type", n => { PremiumType = n.GetIntValue(); } },
                { "primary_guild", n => { PrimaryGuild = n.GetObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild>(global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild.CreateFromDiscriminatorValue); } },
                { "public_flags", n => { PublicFlags = n.GetIntValue(); } },
                { "system", n => { System = n.GetBoolValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
                { "verified", n => { Verified = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accent_color", AccentColor);
            writer.WriteStringValue("avatar", Avatar);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data>("avatar_decoration_data", AvatarDecorationData);
            writer.WriteStringValue("banner", Banner);
            writer.WriteBoolValue("bot", Bot);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles>("collectibles", Collectibles);
            writer.WriteStringValue("discriminator", Discriminator);
            writer.WriteStringValue("email", Email);
            writer.WriteLongValue("flags", Flags);
            writer.WriteStringValue("global_name", GlobalName);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("locale", Locale);
            writer.WriteBoolValue("mfa_enabled", MfaEnabled);
            writer.WriteIntValue("premium_type", PremiumType);
            writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild>("primary_guild", PrimaryGuild);
            writer.WriteIntValue("public_flags", PublicFlags);
            writer.WriteBoolValue("system", System);
            writer.WriteStringValue("username", Username);
            writer.WriteBoolValue("verified", Verified);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserAvatarDecorationResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_avatar_decoration_dataMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserPIIResponse_avatar_decoration_data : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserAvatarDecorationResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserAvatarDecorationResponse? UserAvatarDecorationResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserAvatarDecorationResponse UserAvatarDecorationResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_avatar_decoration_dataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_avatar_decoration_dataMember1? UserPIIResponseAvatarDecorationDataMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_avatar_decoration_dataMember1 UserPIIResponseAvatarDecorationDataMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_avatar_decoration_data();
                if("UserAvatarDecorationResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserAvatarDecorationResponse = new global::Soenneker.Discord.OpenApiClient.Models.UserAvatarDecorationResponse();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserPIIResponseAvatarDecorationDataMember1 = new global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_avatar_decoration_dataMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserAvatarDecorationResponse != null)
                {
                    return UserAvatarDecorationResponse.GetFieldDeserializers();
                }
                else if(UserPIIResponseAvatarDecorationDataMember1 != null)
                {
                    return UserPIIResponseAvatarDecorationDataMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(UserAvatarDecorationResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserAvatarDecorationResponse>(null, UserAvatarDecorationResponse);
                }
                else if(UserPIIResponseAvatarDecorationDataMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_avatar_decoration_dataMember1>(null, UserPIIResponseAvatarDecorationDataMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserCollectiblesResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_collectiblesMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserPIIResponse_collectibles : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserCollectiblesResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserCollectiblesResponse? UserCollectiblesResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserCollectiblesResponse UserCollectiblesResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_collectiblesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_collectiblesMember1? UserPIIResponseCollectiblesMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_collectiblesMember1 UserPIIResponseCollectiblesMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_collectibles();
                if("UserCollectiblesResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserCollectiblesResponse = new global::Soenneker.Discord.OpenApiClient.Models.UserCollectiblesResponse();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserPIIResponseCollectiblesMember1 = new global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_collectiblesMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserCollectiblesResponse != null)
                {
                    return UserCollectiblesResponse.GetFieldDeserializers();
                }
                else if(UserPIIResponseCollectiblesMember1 != null)
                {
                    return UserPIIResponseCollectiblesMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(UserCollectiblesResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserCollectiblesResponse>(null, UserCollectiblesResponse);
                }
                else if(UserPIIResponseCollectiblesMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_collectiblesMember1>(null, UserPIIResponseCollectiblesMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_primary_guildMember1"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPrimaryGuildResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserPIIResponse_primary_guild : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_primary_guildMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_primary_guildMember1? UserPIIResponsePrimaryGuildMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_primary_guildMember1 UserPIIResponsePrimaryGuildMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPrimaryGuildResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UserPrimaryGuildResponse? UserPrimaryGuildResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UserPrimaryGuildResponse UserPrimaryGuildResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse.UserPIIResponse_primary_guild();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserPIIResponsePrimaryGuildMember1 = new global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_primary_guildMember1();
                }
                else if("UserPrimaryGuildResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.UserPrimaryGuildResponse = new global::Soenneker.Discord.OpenApiClient.Models.UserPrimaryGuildResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UserPIIResponsePrimaryGuildMember1 != null)
                {
                    return UserPIIResponsePrimaryGuildMember1.GetFieldDeserializers();
                }
                else if(UserPrimaryGuildResponse != null)
                {
                    return UserPrimaryGuildResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(UserPIIResponsePrimaryGuildMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPIIResponse_primary_guildMember1>(null, UserPIIResponsePrimaryGuildMember1);
                }
                else if(UserPrimaryGuildResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UserPrimaryGuildResponse>(null, UserPrimaryGuildResponse);
                }
            }
        }
    }
}
#pragma warning restore CS0618
