// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Discord.OpenApiClient.Channels.Item.Followers;
using Soenneker.Discord.OpenApiClient.Channels.Item.Invites;
using Soenneker.Discord.OpenApiClient.Channels.Item.Messages;
using Soenneker.Discord.OpenApiClient.Channels.Item.Permissions;
using Soenneker.Discord.OpenApiClient.Channels.Item.Pins;
using Soenneker.Discord.OpenApiClient.Channels.Item.Polls;
using Soenneker.Discord.OpenApiClient.Channels.Item.Recipients;
using Soenneker.Discord.OpenApiClient.Channels.Item.SendSoundboardSound;
using Soenneker.Discord.OpenApiClient.Channels.Item.ThreadMembers;
using Soenneker.Discord.OpenApiClient.Channels.Item.Threads;
using Soenneker.Discord.OpenApiClient.Channels.Item.Typing;
using Soenneker.Discord.OpenApiClient.Channels.Item.Users;
using Soenneker.Discord.OpenApiClient.Channels.Item.Webhooks;
using Soenneker.Discord.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Discord.OpenApiClient.Channels.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \channels\{channel_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithChannel_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The followers property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Followers.FollowersRequestBuilder Followers
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Followers.FollowersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invites property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Invites.InvitesRequestBuilder Invites
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Invites.InvitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The messages property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Messages.MessagesRequestBuilder Messages
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Messages.MessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The permissions property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Permissions.PermissionsRequestBuilder Permissions
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Permissions.PermissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pins property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Pins.PinsRequestBuilder Pins
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Pins.PinsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The polls property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Polls.PollsRequestBuilder Polls
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Polls.PollsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recipients property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Recipients.RecipientsRequestBuilder Recipients
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Recipients.RecipientsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sendSoundboardSound property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.SendSoundboardSound.SendSoundboardSoundRequestBuilder SendSoundboardSound
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.SendSoundboardSound.SendSoundboardSoundRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The threadMembers property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.ThreadMembers.ThreadMembersRequestBuilder ThreadMembers
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.ThreadMembers.ThreadMembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The threads property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Threads.ThreadsRequestBuilder Threads
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Threads.ThreadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The typing property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Typing.TypingRequestBuilder Typing
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Typing.TypingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Discord.OpenApiClient.Channels.Item.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithChannel_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/channels/{channel_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithChannel_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/channels/{channel_id}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Discord.OpenApiClient.Models.RatelimitedResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Discord.OpenApiClient.Models.ErrorResponse">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "429", global::Soenneker.Discord.OpenApiClient.Models.RatelimitedResponse.CreateFromDiscriminatorValue },
                { "4XX", global::Soenneker.Discord.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse>(requestInfo, global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Discord.OpenApiClient.Models.RatelimitedResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Discord.OpenApiClient.Models.ErrorResponse">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "429", global::Soenneker.Discord.OpenApiClient.Models.RatelimitedResponse.CreateFromDiscriminatorValue },
                { "4XX", global::Soenneker.Discord.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse>(requestInfo, global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Discord.OpenApiClient.Models.RatelimitedResponse">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Discord.OpenApiClient.Models.ErrorResponse">When receiving a 4XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse?> PatchAsync(global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse> PatchAsync(global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "429", global::Soenneker.Discord.OpenApiClient.Models.RatelimitedResponse.CreateFromDiscriminatorValue },
                { "4XX", global::Soenneker.Discord.OpenApiClient.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse>(requestInfo, global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithChannel_DeleteResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse? GuildChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse GuildChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse? PrivateChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse PrivateChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse? PrivateGroupChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse PrivateGroupChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse? ThreadResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse ThreadResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_DeleteResponse();
                if("GuildChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GuildChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse();
                }
                else if("PrivateChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PrivateChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse();
                }
                else if("PrivateGroupChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PrivateGroupChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse();
                }
                else if("ThreadResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ThreadResponse = new global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GuildChannelResponse != null)
                {
                    return GuildChannelResponse.GetFieldDeserializers();
                }
                else if(PrivateChannelResponse != null)
                {
                    return PrivateChannelResponse.GetFieldDeserializers();
                }
                else if(PrivateGroupChannelResponse != null)
                {
                    return PrivateGroupChannelResponse.GetFieldDeserializers();
                }
                else if(ThreadResponse != null)
                {
                    return ThreadResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GuildChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse>(null, GuildChannelResponse);
                }
                else if(PrivateChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse>(null, PrivateChannelResponse);
                }
                else if(PrivateGroupChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse>(null, PrivateGroupChannelResponse);
                }
                else if(ThreadResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse>(null, ThreadResponse);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithChannel_GetResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse? GuildChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse GuildChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse? PrivateChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse PrivateChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse? PrivateGroupChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse PrivateGroupChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse? ThreadResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse ThreadResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_GetResponse();
                if("GuildChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GuildChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse();
                }
                else if("PrivateChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PrivateChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse();
                }
                else if("PrivateGroupChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PrivateGroupChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse();
                }
                else if("ThreadResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ThreadResponse = new global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GuildChannelResponse != null)
                {
                    return GuildChannelResponse.GetFieldDeserializers();
                }
                else if(PrivateChannelResponse != null)
                {
                    return PrivateChannelResponse.GetFieldDeserializers();
                }
                else if(PrivateGroupChannelResponse != null)
                {
                    return PrivateGroupChannelResponse.GetFieldDeserializers();
                }
                else if(ThreadResponse != null)
                {
                    return ThreadResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GuildChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse>(null, GuildChannelResponse);
                }
                else if(PrivateChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse>(null, PrivateChannelResponse);
                }
                else if(PrivateGroupChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse>(null, PrivateGroupChannelResponse);
                }
                else if(ThreadResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse>(null, ThreadResponse);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateDMRequestPartial"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateGroupDMRequestPartial"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateGuildChannelRequestPartial"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithChannel_PatchRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateDMRequestPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateDMRequestPartial? UpdateDMRequestPartial { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateDMRequestPartial UpdateDMRequestPartial { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateGroupDMRequestPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateGroupDMRequestPartial? UpdateGroupDMRequestPartial { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateGroupDMRequestPartial UpdateGroupDMRequestPartial { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateGuildChannelRequestPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateGuildChannelRequestPartial? UpdateGuildChannelRequestPartial { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateGuildChannelRequestPartial UpdateGuildChannelRequestPartial { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial? UpdateThreadRequestPartial { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial UpdateThreadRequestPartial { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchRequestBody();
                result.UpdateDMRequestPartial = new global::Soenneker.Discord.OpenApiClient.Models.UpdateDMRequestPartial();
                result.UpdateGroupDMRequestPartial = new global::Soenneker.Discord.OpenApiClient.Models.UpdateGroupDMRequestPartial();
                result.UpdateGuildChannelRequestPartial = new global::Soenneker.Discord.OpenApiClient.Models.UpdateGuildChannelRequestPartial();
                result.UpdateThreadRequestPartial = new global::Soenneker.Discord.OpenApiClient.Models.UpdateThreadRequestPartial();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(UpdateDMRequestPartial != null || UpdateGroupDMRequestPartial != null || UpdateGuildChannelRequestPartial != null || UpdateThreadRequestPartial != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(UpdateDMRequestPartial, UpdateGroupDMRequestPartial, UpdateGuildChannelRequestPartial, UpdateThreadRequestPartial);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.UpdateDMRequestPartial>(null, UpdateDMRequestPartial, UpdateGroupDMRequestPartial, UpdateGuildChannelRequestPartial, UpdateThreadRequestPartial);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse"/>, <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithChannel_PatchResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse? GuildChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse GuildChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse? PrivateChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse PrivateChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse? PrivateGroupChannelResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse PrivateGroupChannelResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse? ThreadResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse ThreadResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Discord.OpenApiClient.Channels.Item.WithChannel_ItemRequestBuilder.WithChannel_PatchResponse();
                if("GuildChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GuildChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse();
                }
                else if("PrivateChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PrivateChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse();
                }
                else if("PrivateGroupChannelResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.PrivateGroupChannelResponse = new global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse();
                }
                else if("ThreadResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ThreadResponse = new global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GuildChannelResponse != null)
                {
                    return GuildChannelResponse.GetFieldDeserializers();
                }
                else if(PrivateChannelResponse != null)
                {
                    return PrivateChannelResponse.GetFieldDeserializers();
                }
                else if(PrivateGroupChannelResponse != null)
                {
                    return PrivateGroupChannelResponse.GetFieldDeserializers();
                }
                else if(ThreadResponse != null)
                {
                    return ThreadResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GuildChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.GuildChannelResponse>(null, GuildChannelResponse);
                }
                else if(PrivateChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PrivateChannelResponse>(null, PrivateChannelResponse);
                }
                else if(PrivateGroupChannelResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.PrivateGroupChannelResponse>(null, PrivateGroupChannelResponse);
                }
                else if(ThreadResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Discord.OpenApiClient.Models.ThreadResponse>(null, ThreadResponse);
                }
            }
        }
    }
}
#pragma warning restore CS0618
