// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Discord.OpenApiClient.PartnerSdk.Dms.Item.Item.Messages.Item.ModerationMetadata;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Discord.OpenApiClient.PartnerSdk.Dms.Item.Item.Messages.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \partner-sdk\dms\{user_id_1}\{user_id_2}\messages\{message_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMessage_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The moderationMetadata property</summary>
        public global::Soenneker.Discord.OpenApiClient.PartnerSdk.Dms.Item.Item.Messages.Item.ModerationMetadata.ModerationMetadataRequestBuilder ModerationMetadata
        {
            get => new global::Soenneker.Discord.OpenApiClient.PartnerSdk.Dms.Item.Item.Messages.Item.ModerationMetadata.ModerationMetadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.PartnerSdk.Dms.Item.Item.Messages.Item.WithMessage_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMessage_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Discord.OpenApiClient.PartnerSdk.Dms.Item.Item.Messages.Item.WithMessage_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMessage_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/partner-sdk/dms/{user_id_1}/{user_id_2}/messages/{message_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
